 datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ssmms-sql?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 8888
