spring:
 	datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            url: jdbc:mysql://localhost:3306/ssmms-sql?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
            username: root
            password: 8888